version: 2
updates:
  # Go modules in test-go/ subdirectory
  - package-ecosystem: "gomod"
    directory: "/test-go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "annabarnes1138"
    assignees:
      - "annabarnes1138"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "puck"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "annabarnes1138"
    assignees:
      - "annabarnes1138"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "annabarnes1138"
    assignees:
      - "annabarnes1138"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"