name: Security Scanning

on:
  schedule:
    # Weekly security scan on Sundays at 2:30 AM UTC
    - cron: '30 2 * * 0'
  workflow_dispatch:

jobs:
  security:
    name: Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'go'
      go-version: '1.25.1'
      working-directory: 'test-go'
      system-packages: 'portaudio19-dev'
    secrets: inherit